### PR TITLE
fix: Removed ThreadListener as it was UNIFINISHED

### PR DESCRIPTION
**Pull request by Dawsson**
DO U APPROVE????? @akkkih

### CODE REVIEW

**Review by awkkih — APPROVED** [review]

**Comment by Dawsson** [comment]
hi, cvan I pls merge???

**Comment by stephendotgg** [comment]
There is a revert button

**Comment by Dawsson** [comment]
ur joking

**Comment by stephendotgg** [comment]
Brother

**Comment by Dawsson** [comment]
we learn something new every day

**Pull request merged**
