### PR TITLE
New responses when /verifyother is used + messages are now deleted in #verify upon verification

### LINKED ISSUE #29: [Enhancement]: make /verifyother nicer
### Explain your idea.

as of now, /verifyother works fine, but it could be enhanced.

- The message currently says you have been verified, this is obviously incorrect. I would suggest changing this to "[name] has successfully been verified.".
- /verifyother could potentially remove every message from the targeted user in the verified channel. The lazy way to do this is delete all their messages in the channel this command is ran in, but this is asking for problems. Adding a env variable for the verified channel and then deleting all messages there from the targeted user would be the way to do this i suppose.

### How could you do this differently

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Zcamt**
This should accommodate #29 for both the QOL aspect of more accurate responses to the commandsender and functional aspect of messages being deleted automatically from #verify

### CODE REVIEW

**Comment by Zcamt** [comment]
When I run the verifyStudent test locally it works, not entirely sure why it fails here, maybe because of the environment variables not working when the test is run in a job like this?

**Comment by Nuckerr** [comment]
The workflows have been updated, try pulling from upstream to your fork, see if that fixes workflows

**Comment by Zcamt** [comment]
> The workflows have been updated, try pulling from upstream to your fork, see if that fixes workflows

Didn't seem to fix it

**Comment by Nuckerr** [comment]
oh I know the issue. The udemy credentials are stored in secrets on this repo, but you have a fork. Lemme fix this rq

**Review by Nuckerr — APPROVED** [review]
Code looks good.
Tested, seems to work fine

**Pull request merged**
