### PR TITLE
Add 💯 when someone counts to a multiple of 100

### PR DESCRIPTION
**Pull request by BennettSchwartz**
ok for real this time :) When someone messes up, they are given the "idiot" role. Every 100, the "💯" emoji is reacted.

### CODE REVIEW

**Comment by BennettSchwartz** [comment]
I apologize for my atrocious actions and even thinking about making people have the idiot role. I will be removing it :)

**Comment by stephendotgg** [comment]
Still WIP?

**Comment by BennettSchwartz** [comment]
Yeah, sorry. I forgot about this. I'll do it now.

**Comment by BennettSchwartz** [comment]
should be fixed

**Comment by Dawsson** [comment]
can u put it ong it works

**Comment by Dawsson** [comment]
Remove the idiot role and ill merge. We can have the idiot role still, but we don't want to make it after 1 fuck up

**Review by Dawsson — APPROVED** [review]

**Pull request merged**
