### PR TITLE
/repleaderboard now uses mentions + leaderboard now shows "last updated" with localized timestamp

### LINKED ISSUE #5: Rep leaderboard should do mentions
### Explain the issue.

Rep leaderboard should do mentions instead of just text names.

### How to recreate?

/repleaderboard

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Zcamt**
This fixes #5

### CODE REVIEW

**Comment by Zcamt** [comment]
This now also fixes #9

**Review by joshdevous — COMMENTED** [review]
If you're up for it, I think this would look better if it matched what we have in #leaderboard honestly, just without the last updated timestamps.

**Comment by sttephen** [comment]
+1 ^

**Comment by Zcamt** [comment]
> If you're up for it, I think this would look better if it matched what we have in #leaderboard honestly, just without the last updated timestamps.

Sure, also want the medals added then correct?

**Comment by joshdevous** [comment]
> > If you're up for it, I think this would look better if it matched what we have in #leaderboard honestly, just without the last updated timestamps.
> 
> Sure, also want the medals added then correct?

Yessir please

**Review by Nuckerr — APPROVED** [review]
Good idea about timestamls

**Pull request merged**
