### PR TITLE
Fuzzy search for lectures and quizes.

### PR DESCRIPTION
**Pull request by revelcw**
Improve /lecture command using [fuzzywuzzy](https://github.com/xdrop/fuzzywuzzy). No problems so far and misspellings work extremely well. Also works with /quiz. 

Examples:
image
image
image
image

### CODE REVIEW

**Comment by Nuckerr** [comment]
I'll review this after I merge #61. I assume this can easily be merged. So when that is merged, feel free to pull and merge that and then I'll review it with help from @MLGPenguin

**Comment by revelcw** [comment]
> I'll review this after I merge #61. I assume this can easily be merged. So when that is merged, feel free to pull and merge that and then I'll review it with help from @MLGPenguin

This has a different implementation than penguins and would likely create merge conflicts.

**Comment by Nuckerr** [comment]
Okay, well if you can try and resolve them when that merges to master (hopefully tonight or tommorow GMT)

**Comment by revelcw** [comment]
> 

Well, my code is just another way of doing penguin's code. It would be one or the other. Mine is more readable but does use an external package.

**Comment by Nuckerr** [comment]
I believe penguin's code does also improve the logic of the search system on top of allowing for spelling mistakes. If so, we will probably take penguin's, sorry. @MLGPenguin do you mind taking a look at this pr

**Comment by MLGPenguin** [comment]
> > 
> 
> Well, my code is just another way of doing penguin's code. It would be one or the other. Mine is more readable but does use an external package.

Unfortunately one or the other is the case, I'd disagree yours is more readable but that's a quarrell I don't wish to start. 
My implementation is from the ground up which means we can modify it and refine it to suit our needs if we decide its not working perfectly, whereas as stated yours uses an external package which may not be modified. For this reason I think it'd be best to take mine (and I was first 😉).
@Nuckerr 

I also don't see any major functional benefits in search queries, in-fact from what I can see mine even handles partial-queries better since I built it with that specifically in mind.

**Comment by Nuckerr** [comment]
Sadly I think we'll be taking #61's version of this

**Pull request closed without merging**
