### PR TITLE
Send message when help post is created

### PR DESCRIPTION
**Pull request by awkkih**
Currently looks like this
image

### CODE REVIEW

**Comment by Dawsson** [comment]
@akkkih hi, were u meant to fix merge issues?

**Comment by awkkih** [comment]
I highly need someone to try and finish this for me, I literally cannot find a way of doing it.

**Review by Dawsson — APPROVED** [review]
I (regrettingly) approve of a commit history which does NOT follow our guidelines

**Comment by Pan-nav** [comment]
> I highly need someone to try and finish this for me, I literally cannot find a way of doing it.

Hey! Feel free to create a help post at https://discord.com/channels/397526357191557121/1019977402002190426 and one of our goated staff members will be on our way to help you!

**Pull request merged**
