### PR TITLE
Lecture Searching Improvements

### LINKED ISSUE #31: [Bug]: Lecture searching needs improving
### Explain the issue.

whenever i type lecture name specficlly and correctly it gives me another lecture that isnt even close to the search  

### How to recreate?

search anything 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MLGPenguin**
fixing #31 

This PR aims to address the long-awaited lecture command issues by implementing a new lecture searching algorithm.

As there are many people in the discord who speak English as their second language, I took extra consideration to design the searcher to be lenient of spelling mistakes and still provide accurate results when provided a portion of a title (even if it's misspelt).

Disclaimer; _The searching algorithm has been tested on sample data, however, the bot functionality has not yet been tested due to my lack of knowledge regarding... doing that..._ 😄

### CODE REVIEW

**Review by Nuckerr — APPROVED** [review]
Even documeneted!

**Comment by Nuckerr** [comment]
Mind sending your test queries?

**Comment by MLGPenguin** [comment]
> Even documeneted!

Of course, I'm no novice ;)

> Mind sending your test queries?

[testcases.txt](https://github.com/learnspigot/discord-bot/files/10282789/testcases.txt)
Here's a few! (Should have attached these initially but I forgot, sorry)

**Comment by sttephen** [comment]
Great job!

**Comment by Nuckerr** [comment]
Thanks, I'll test this in discord and then merge

**Comment by Nuckerr** [comment]
image
Not a massive error as it shows it under the other lectures

**Comment by Nuckerr** [comment]
Looks good, we can always make improvements later down the road as need be.

**Comment by MLGPenguin** [comment]
> image
> Not a massive error as it shows it under the other lectures

That's certainly odd.. did you find any other discrepancies with anything else?

**Comment by Nuckerr** [comment]
image
Just this I think

**Comment by Nuckerr** [comment]
Didn't test them all

**Comment by MLGPenguin** [comment]
> Didn't test them all
> 

Alright, those were the two worst test cases anyway. And the fact they both show up in the top 4 means it's not far off.

From what I can see the issue arises when it's a misspelt partial query, misspelt full queries and correctly spelt partial queries should work as intended.

If there is demand I will work on a fix, otherwise this should be sufficient for the time being.

**Pull request merged**
