### PR TITLE
Rep command now shows 10 reps and supports pages

### LINKED ISSUE #91: [Enhancement]: Ability to list your recent rep
### Explain your idea.

Basically similar to how /rep shows your most recent 3 rep, a command which shows your previous 10, maybe with back and forward buttons to go 10-20, 20-30 and so on. so you can view all your rep, who gave it to you, and the channel name, etc.

Similar to the existing rep command;
image

### How could you do this differently

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Zcamt**
This closes #91

This is how it looks:
image
Edit: Embed color has been fixed

### CODE REVIEW

**Comment by Zcamt** [comment]
I see now, that the original issue created by Penguin mentions showing 10 reps at a time, this can also be done - I had just not seen that when I made this and just decided on 5.

**Comment by sttephen** [comment]
@Zcamt Looks awesome :)

**Review by Nuckerr — APPROVED** [review]
Great job! Looks good

**Comment by Nuckerr** [comment]
Only thing is I get this error changing page. I only have one page of rep:
```
java.lang.IllegalArgumentException: fromIndex(10) > toIndex(3)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.AbstractList.subList(AbstractList.java:497)
	at com.learnspigot.bot.command.ReputationCommand.generateRepEmbed(ReputationCommand.kt:95)
	at com.learnspigot.bot.command.ReputationCommand.access$generateRepEmbed(ReputationCommand.kt:41)
	at com.learnspigot.bot.command.ReputationCommand$repCommand$1$1$invokeSuspend$$inlined$listener-Kx4hsE0$default$1.onEvent(CoroutineEventManager.kt:158)
	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener$suspendImpl(CoroutineEventManager.kt:101)
	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener(CoroutineEventManager.kt)
	at dev.minn.jda.ktx.events.CoroutineEventManager$handle$1.invokeSuspend(CoroutineEventManager.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Zcamt** [comment]
> Only thing is I get this error changing page. I only have one page of rep:
> 
> ```
> java.lang.IllegalArgumentException: fromIndex(10) > toIndex(3)
> 	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
> 	at java.base/java.util.AbstractList.subList(AbstractList.java:497)
> 	at com.learnspigot.bot.command.ReputationCommand.generateRepEmbed(ReputationCommand.kt:95)
> 	at com.learnspigot.bot.command.ReputationCommand.access$generateRepEmbed(ReputationCommand.kt:41)
> 	at com.learnspigot.bot.command.ReputationCommand$repCommand$1$1$invokeSuspend$$inlined$listener-Kx4hsE0$default$1.onEvent(CoroutineEventManager.kt:158)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener$suspendImpl(CoroutineEventManager.kt:101)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener(CoroutineEventManager.kt)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager$handle$1.invokeSuspend(CoroutineEventManager.kt:91)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```

Ah shit - will fix that

**Comment by Zcamt** [comment]
That should fix it :) Works on my end atleast

**Pull request merged**
