### PR TITLE
feat(counting): add insults for when a user fails on counting or coun…

### PR DESCRIPTION
**Pull request by cirosanchez**
Added a bunch of ChatGPT generated insults and just send them randomly in both cases the user fucks up when counting.

### CODE REVIEW

**Comment by StillLutto** [comment]
A thing I did was adding {username} or {count} things in the messages themselves. You can then replace those on run with their respective username and current count. Also, love the messages lol

**Comment by cirosanchez** [comment]
OOOH YEA, GOOD IDEA

**Comment by lenbot7** [comment]
YES WE NEED THIS

**Review by Dawsson — APPROVED** [review]
Very interesting changes, lets test on main 😉

**Comment by Dawsson** [comment]
image

**Pull request merged**
