### PR TITLE
Change starboard embed layout

### PR DESCRIPTION
**Pull request by awkkih**
Here's a preview on what it looks like now: 
- If it's not been edited:
image 
- If it has been edited (any timeframe):
image

### CODE REVIEW

**Comment by revelcw** [comment]
I'd remove the "before", it sounds really wordy.  More like, "This message has been edited" or "Original message edited" would seem cleaner.

**Comment by awkkih** [comment]
Alright, changed. Do you think anything else would be needed?

**Comment by revelcw** [comment]
> Alright, changed. Do you think anything else would be needed?

If you set the footer to "" does it disappear or put an empty footer? Wouldn't you use null for that?

**Comment by awkkih** [comment]
It's as shown in the picture

**Comment by revelcw** [comment]
> It's as shown in the picture

lgtm then

**Comment by stephendotgg** [comment]
Nice

**Pull request merged**
