### PR TITLE
Improved the message sent upon ticket closure

### LINKED ISSUE #83: Improve select contributors message
### Explain your idea.

Before the contributor selector when closing a ticket, the message says something like "Please select contributors below".

Could you change this to:

"Please select contributors below. These should be people who have helped **solve your actual question**."

### How could you do this differently

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Zcamt**
This closes #83 

New look of the message:
image

### CODE REVIEW

**Comment by sttephen** [comment]
@Zcamt I hate to be that guy... but mind adding periods?

**Comment by sttephen** [comment]
Otherwise looks great! Will leave for Nucker

**Comment by Zcamt** [comment]
> @Zcamt I hate to be that guy... but mind adding periods?

It's okay being that guy, will do haha

**Comment by Zcamt** [comment]
Done, think I forgot all about them as the old message didn't have any either

**Comment by sttephen** [comment]
> Done, think I forgot all about them as the old message didn't have any either

Yeah, I was gonna make an issue but I figured this would override it. GJ!

**Comment by Nuckerr** [comment]
Issue 100 🎉🎉🎊🪅

**Review by Nuckerr — APPROVED** [review]

**Pull request merged**
